import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import java.security.MessageDigest

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
}

/**
 * Copies the on-device ADB helper APK (built by `:helper`) into a Compose
 * resources directory and generates `AdbHelperArtifact` with its SHA-256, so
 * the desktop/web clients can tell whether the copy on a device is current,
 * and the lowest SDK it runs on.
 */
abstract class PrepareAdbHelper : DefaultTask() {
    @get:InputFiles
    abstract val apkDirectory: ConfigurableFileCollection

    @get:Input
    abstract val minSdk: Property<Int>

    @get:OutputDirectory
    abstract val resourcesDirectory: DirectoryProperty

    @get:OutputDirectory
    abstract val sourcesDirectory: DirectoryProperty

    @TaskAction
    fun prepare() {
        val apk = apkDirectory.asFileTree.matching { include("*.apk") }.singleFile
        val bytes = apk.readBytes()
        val sha256 = MessageDigest.getInstance("SHA-256").digest(bytes)
            .joinToString("") { "%02x".format(it) }

        resourcesDirectory.get().asFile.resolve("files").apply {
            deleteRecursively()
            mkdirs()
            resolve("canta-helper.apk").writeBytes(bytes)
        }
        sourcesDirectory.get().asFile.resolve("io/github/samolego/canta/core/adb").apply {
            deleteRecursively()
            mkdirs()
            resolve("AdbHelperArtifact.kt").writeText(
                """
                |// Generated by the prepareAdbHelper task. Do not edit.
                |package io.github.samolego.canta.core.adb
                |
                |internal object AdbHelperArtifact {
                |    /** Compose resource path of the bundled helper APK. */
                |    const val RESOURCE_PATH = "files/canta-helper.apk"
                |    const val SHA256 = "$sha256"
                |    /** Devices on older Android versions are refused. */
                |    const val MIN_SDK = ${minSdk.get()}
                |}
                |""".trimMargin()
            )
        }
    }
}

/** Generates `BuildInfo` with the app version from `gradle.properties`, for every target. */
@CacheableTask
abstract class GenerateBuildInfo : DefaultTask() {
    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<Int>

    @get:OutputDirectory
    abstract val sourcesDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        sourcesDirectory.get().asFile.resolve("io/github/samolego/canta").apply {
            deleteRecursively()
            mkdirs()
            resolve("BuildInfo.kt").writeText(
                """
                |// Generated by the generateBuildInfo task. Do not edit.
                |package io.github.samolego.canta
                |
                |object BuildInfo {
                |    const val VERSION_NAME = "${versionName.get()}"
                |    const val VERSION_CODE = ${versionCode.get()}
                |}
                |""".trimMargin()
            )
        }
    }
}

val generateBuildInfo = tasks.register<GenerateBuildInfo>("generateBuildInfo") {
    versionName.set(providers.gradleProperty("version_name"))
    versionCode.set(providers.gradleProperty("version_code").map(String::toInt))
    sourcesDirectory.set(layout.buildDirectory.dir("generated/buildInfo/kotlin"))
}

val adbHelperApk = configurations.create("adbHelperApk") {
    isCanBeConsumed = false
    isCanBeResolved = true
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage::class, "canta-adb-helper-apk"))
    }
}

dependencies {
    adbHelperApk(project(":helper"))
}

val prepareAdbHelper = tasks.register<PrepareAdbHelper>("prepareAdbHelper") {
    apkDirectory.from(adbHelperApk)
    minSdk.set(libs.versions.android.minSdk.get().toInt())
    resourcesDirectory.set(layout.buildDirectory.dir("generated/adbHelper/resources"))
    sourcesDirectory.set(layout.buildDirectory.dir("generated/adbHelper/kotlin"))
}

compose {
    resources {
        packageOfResClass = "io.github.samolego.canta.generated.resources"
        // Only the ADB-backed targets ship the helper; Android reads packages
        // in-process and never needs it.
        customDirectory(
            sourceSetName = "adbMain",
            directoryProvider = prepareAdbHelper.flatMap { it.resourcesDirectory },
        )
    }
}

kotlin {
    jvmToolchain(libs.versions.jvm.get().toInt())

    android {
        namespace = "io.github.samolego.canta.compose"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        // Package Compose resources into the Android assets.
        androidResources {
            enable = true
        }
    }

    jvm("desktop")

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }


    tasks.named("wasmJsBrowserTest") {
        enabled = false
    }

    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("jvmCommon") {
                // No dedicated matcher exists for the
                // com.android.kotlin.multiplatform.library target yet.
                withCompilations { it.target.platformType == KotlinPlatformType.androidJvm }
                withJvm()
            }
            // Targets that manage a device over ADB (desktop via dadb, web via
            // WebUSB) rather than in-process.
            group("adb") {
                withJvm()
                withWasmJs()
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildInfo.flatMap { it.sourcesDirectory })
            dependencies {
                // api: the app modules only depend on :composeApp for Compose.
                api(compose.runtime)
                api(compose.foundation)
                api(compose.material3)
                api(compose.ui)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)

                implementation(libs.androidx.lifecycle.viewmodel.compose)
                implementation(libs.androidx.lifecycle.runtime.compose)
                implementation(libs.androidx.navigation.compose)

                implementation(project(":packages"))
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.datetime)
                implementation(libs.ktor.client.core)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        named("adbMain") {
            kotlin.srcDir(prepareAdbHelper.flatMap { it.sourcesDirectory })
        }
        named("jvmCommonMain").dependencies {
            // Shared by androidMain and desktopMain.
            implementation(libs.ktor.client.okhttp)
        }
        androidMain.dependencies {
            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.biometric)
            implementation(libs.shizuku.api)
            implementation(libs.hiddenapibypass)
        }
        named("desktopMain").dependencies {
            implementation(compose.desktop.common)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.dadb)
        }
        named("desktopTest").dependencies {
            // Skia's native library, for tests that decode images.
            implementation(compose.desktop.currentOs)
        }
        wasmJsMain.dependencies {
            implementation(npm("@yume-chan/adb", "2.6.4"))
            implementation(npm("@yume-chan/adb-daemon-webusb", "2.3.2"))
            implementation(npm("@yume-chan/adb-credential-web", "2.1.0"))
        }
    }
}
