import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

// Release signing: CI writes key.properties (storeFile, storePassword,
// keyAlias, keyPassword); without it, release builds are left unsigned.
val keystoreProperties = Properties().apply {
    rootProject.file("key.properties").takeIf { it.exists() }?.inputStream()?.use(::load)
}

android {
    namespace = "io.github.samolego.canta"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    // Reproducible builds (F-Droid): no dependency metadata blobs.
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    defaultConfig {
        applicationId = "io.github.samolego.canta"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = providers.gradleProperty("version_code").get().toInt()
        versionName = providers.gradleProperty("version_name").get()
    }

    signingConfigs {
        if (!keystoreProperties.isEmpty) {
            create("release") {
                storeFile = file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.findByName("release")
        }
    }

    buildFeatures {
        compose = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

/**
 * Generates `res/xml/locales_config.xml` (Android 13+ per-app language
 * picker) from the Compose resource folders, where the translations live,
 * e.g. `values-pt-rBR` → `pt-BR`.
 */
@CacheableTask
abstract class GenerateLocaleConfig : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val translationDirs: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val tags = translationDirs.files
            .map { it.name.removePrefix("values-").replace("-r", "-") }
            .sorted()
        val locales = (listOf("en") + tags).joinToString("\n") { "    <locale android:name=\"$it\" />" }
        outputDirectory.get().asFile.resolve("xml").apply {
            mkdirs()
            resolve("locales_config.xml").writeText(
                """
                |<?xml version="1.0" encoding="utf-8"?>
                |<!-- Generated by the generateLocaleConfig task. Do not edit. -->
                |<locale-config xmlns:android="http://schemas.android.com/apk/res/android">
                |$locales
                |</locale-config>
                |""".trimMargin()
            )
        }
    }
}

val generateLocaleConfig = tasks.register<GenerateLocaleConfig>("generateLocaleConfig") {
    translationDirs.from(
        rootProject.fileTree("composeApp/src/commonMain/composeResources") { include("values-*/strings.xml") }
            .elements.map { files -> files.map { it.asFile.parentFile } }
    )
    outputDirectory.set(layout.buildDirectory.dir("generated/localeConfig/res"))
}

kotlin {
    jvmToolchain(libs.versions.jvm.get().toInt())
}

androidComponents.onVariants { variant ->
    variant.sources.res?.addGeneratedSourceDirectory(generateLocaleConfig, GenerateLocaleConfig::outputDirectory)
}

dependencies {
    implementation(project(":composeApp"))

    // Required by the ShizukuProvider declared in AndroidManifest.xml.
    implementation(libs.shizuku.provider)

    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.fragment)
}
